project_name: mission-toolkit

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: m
    ldflags:
      - -s -w
      - -X github.com/dnatag/mission-toolkit/internal/version.Version={{.Version}}
      - -X github.com/dnatag/mission-toolkit/internal/version.Commit={{.Commit}}
      - -X github.com/dnatag/mission-toolkit/internal/version.Date={{.Date}}

archives:
  - format: zip
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
    builds:
      - default

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: dnatag
    name: mission-toolkit
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
